# SwifterSockets document generator jazzy settings

copyright: Copyright 2016-2017 rien@balancingrock.nl
author: Balancingrock
author_url: balancingrock.nl
module: SwifterSockets
documentation: docs/*.md
hide_documentation_coverage: false
xcodebuild_arguments: [-target, SwifterSockets]
github_url: https://github.com/Balancingrock/SwifterSockets
output: ~/Documents/Websites/swiftfire.nl/projects/swiftersockets/reference
clean: true
theme: fullwidth
